targets:
  $default:
    builders:
      riverpod_generator:riverpod_generator:
        generate_for:
          - lib/providers/**.dart
          - lib/repositories/**.dart
          - lib/services/**.dart
          - lib/ui/**.dart 
          - lib/viewmodels/**.dart 
          - lib/controllers/**.dart
        options:
          # Riverpod generator options can be specified here if needed.
          # output: .riverpod.dart