workflows:
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - supabase_credentials
        - app_store_credentials
        - ios_credentials # Contains certificate, profile, and passwords
      vars:
        BUNDLE_ID: "ai.vuet.vuet"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Developer/Xcode/DerivedData
        - $CM_BUILD_DIR/ios/Pods
    scripts:
      - name: Set up code signing
        script: |
          # Debug info
          echo "Setting up code signing..."
          
          # Create directories
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          
          # Write the provisioning profile directly from environment variable
          echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
          
          # Write the certificate to a file
          echo "$CERTIFICATE" | base64 --decode > /tmp/certificate.p12
          
          # Set up the keychain and add the certificate
          keychain initialize
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password "$CERTIFICATE_PASSWORD"
          
          # Use app-store-connect to fetch the profiles - this is a fallback if the profile doesn't work
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          
          # Configure the Xcode project to use our provisioning profile
          cd ios
          xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter pub get
      - name: Generate code
        script: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
      - name: Setup environment variables for the app
        script: |
          echo "Setting up environment variables for the app..."
          if [ -f ".env.production" ]; then
            cp .env.production .env
            echo "Copied .env.production to .env"
          elif [ -f ".env.development" ]; then
            cp .env.development .env
            echo "Warning: .env.production not found. Copied .env.development to .env for branch $CM_BRANCH"
          else
            echo "Error: Neither .env.production nor .env.development found at the repository root."
            echo "Please ensure one of these files exists in your vuetapp.git repository."
            exit 1
          fi
      - name: Set iOS build number
        script: |
          cd ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          agvtool new-version -all $NEW_BUILD_NUMBER
          echo "Set iOS build number to $NEW_BUILD_NUMBER"
      - name: Flutter build iOS for release
        script: |
          flutter build ios --release
      - name: Build and sign IPA
        script: |
          cd ios
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $CM_BUILD_DIR/flutter_drive.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_P8_CONTENT
        key_id: $APPLE_KEY_ID
        issuer_id: $APPLE_ISSUER_ID
        submit_to_testflight: true
