name: vuet_app
description: "Vuet App - Supabase & Flutter Implementation"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Adding scripts section for easy access to common commands
scripts:
  coderabbit: dart scripts/run_coderabbit.dart

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1  # Add Google Fonts package
  # Supabase for backend and auth
  supabase_flutter: ^2.9.0
  firebase_core: ^2.30.0 # Added firebase_core
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2 # Consider updating to a more recent version like ^0.19.0 if compatible, or ^0.18.1
  equatable: ^2.0.7 # This is an older version, latest is ^2.0.5
  # uni_links: ^0.5.1 # This package is discontinued, consider migrating to app_links - commented out due to namespace issues
  flutter_local_notifications: ^19.2.0 # Consider updating to latest, e.g., ^17.0.0 or higher
  # flutter_vibrate: ^1.3.0  # Temporarily commented out due to namespace issues in build.gradle
  uuid: ^4.3.3
  provider: ^6.1.1 # Legacy provider, still used in main.dart for some services
  timezone: ^0.10.1 # Consider updating to latest, e.g., ^0.9.2
  go_router: ^15.1.2 # Consider updating to latest, e.g., ^14.0.0 or higher
  table_calendar: ^3.1.0 # Consider updating to latest, e.g., ^3.1.1
  url_launcher: ^6.2.5 # Added for launching URLs like phone calls

  # Code generation dependencies
  freezed_annotation: ^2.4.1 # Keeping this, activeContext didn't specify annotation for freezed
  json_annotation: ^4.9.0 # Keeping this, activeContext didn't specify annotation for json_serializable
  riverpod_annotation: ^2.3.3 # From activeContext

  # Added packages
  flutter_riverpod: ^2.4.9 # From activeContext
  riverpod: ^2.4.9 # Aligning with flutter_riverpod
  path: ^1.9.0 # For path operations
  image_picker: ^1.0.7 # Or latest stable version
  js: ^0.6.7 # For JavaScript interop (compatible with flutter_secure_storage)
  logger: ^2.5.0 # Added logger package
  flutter_colorpicker: ^1.1.0 # For color selection in account settings
  email_validator: ^2.1.17 # For email validation in contact settings
  shimmer: ^3.0.0 # For loading skeleton animations
  http: ^1.1.0 # For HTTP requests to AI APIs
  markdown: ^7.1.1 # For markdown rendering in chat
  speech_to_text: ^6.6.0 # For voice input
  flutter_tts: ^3.8.5 # For text-to-speech
  file_picker: ^8.0.0 # For file uploads
  # Performance and monitoring dependencies
  cached_network_image: ^3.3.1 # For optimized image loading and caching
  flutter_cache_manager: ^3.3.1 # For advanced caching
  visibility_detector: ^0.4.0+2 # For lazy loading detection
  icalendar_parser: ^2.1.0 # For parsing iCalendar (.ics) files

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Consider updating to latest, e.g., ^4.0.0

  # Code generation dependencies
  build_runner: ^2.4.7 # From activeContext
  freezed: ^2.4.6      # From activeContext
  json_serializable: ^6.7.1 # From activeContext
  riverpod_generator: ^2.3.9 # From activeContext

flutter:
  uses-material-design: true
  
  assets:
    - .env.development
    - .env.production
    - assets/
    - assets/images/
    - assets/images/categories/
    - assets/FontManifest.json
  
  # Use Google Fonts instead of local font files
  fonts: []
