// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'entity_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$BaseEntityModelImpl _$$BaseEntityModelImplFromJson(
        Map<String, dynamic> json) =>
    _$BaseEntityModelImpl(
      id: json['id'] as String?,
      name: json['name'] as String,
      description: json['description'] as String?,
      userId: json['user_id'] as String,
      appCategoryId: (json['app_category_id'] as num?)?.toInt(),
      categoryId: json['category_id'] as String?,
      imageUrl: json['imageUrl'] as String?,
      parentId: json['parentId'] as String?,
      subtype: $enumDecode(_$EntitySubtypeEnumMap, json['subtype']),
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: json['updated_at'] == null
          ? null
          : DateTime.parse(json['updated_at'] as String),
      isHidden: json['isHidden'] as bool?,
      customFields: json['custom_fields'] as Map<String, dynamic>?,
      attachments: (json['attachments'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      dueDate: json['due_date'] == null
          ? null
          : DateTime.parse(json['due_date'] as String),
      status: json['status'] as String?,
      subcategoryId: json['subcategory_id'] as String?,
    );

Map<String, dynamic> _$$BaseEntityModelImplToJson(
        _$BaseEntityModelImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'description': instance.description,
      'user_id': instance.userId,
      'app_category_id': instance.appCategoryId,
      'category_id': instance.categoryId,
      'imageUrl': instance.imageUrl,
      'parentId': instance.parentId,
      'subtype': _$EntitySubtypeEnumMap[instance.subtype]!,
      'created_at': instance.createdAt.toIso8601String(),
      'updated_at': instance.updatedAt?.toIso8601String(),
      'isHidden': instance.isHidden,
      'custom_fields': instance.customFields,
      'attachments': instance.attachments,
      'due_date': instance.dueDate?.toIso8601String(),
      'status': instance.status,
      'subcategory_id': instance.subcategoryId,
    };

const _$EntitySubtypeEnumMap = {
  EntitySubtype.academicPlan: 'AcademicPlan',
  EntitySubtype.courseWork: 'CourseWork',
  EntitySubtype.extracurricularPlan: 'ExtracurricularPlan',
  EntitySubtype.school: 'School',
  EntitySubtype.student: 'Student',
  EntitySubtype.subject: 'Subject',
  EntitySubtype.teacher: 'Teacher',
  EntitySubtype.tutor: 'Tutor',
  EntitySubtype.schoolBreak: 'SchoolBreak',
  EntitySubtype.schoolTerm: 'SchoolTerm',
  EntitySubtype.schoolTermEnd: 'SchoolTermEnd',
  EntitySubtype.schoolTermStart: 'SchoolTermStart',
  EntitySubtype.schoolYearEnd: 'SchoolYearEnd',
  EntitySubtype.schoolYearStart: 'SchoolYearStart',
  EntitySubtype.anniversary: 'Anniversary',
  EntitySubtype.anniversaryPlan: 'AnniversaryPlan',
  EntitySubtype.birthday: 'Birthday',
  EntitySubtype.event: 'Event',
  EntitySubtype.guestListInvite: 'GuestListInvite',
  EntitySubtype.hobby: 'Hobby',
  EntitySubtype.holiday: 'Holiday',
  EntitySubtype.holidayPlan: 'HolidayPlan',
  EntitySubtype.socialMedia: 'SocialMedia',
  EntitySubtype.socialPlan: 'SocialPlan',
  EntitySubtype.eventSubentity: 'EventSubentity',
  EntitySubtype.petBirthday: 'PetBirthday',
  EntitySubtype.pet: 'Pet',
  EntitySubtype.vet: 'Vet',
  EntitySubtype.walker: 'Walker',
  EntitySubtype.groomer: 'Groomer',
  EntitySubtype.sitter: 'Sitter',
  EntitySubtype.microchipCompany: 'MicrochipCompany',
  EntitySubtype.insuranceCompany: 'InsuranceCompany',
  EntitySubtype.insurancePolicy: 'InsurancePolicy',
  EntitySubtype.colleague: 'Colleague',
  EntitySubtype.work: 'Work',
  EntitySubtype.careerGoal: 'CareerGoal',
  EntitySubtype.daysOff: 'DaysOff',
  EntitySubtype.employee: 'Employee',
  EntitySubtype.beautySalon: 'BeautySalon',
  EntitySubtype.dentist: 'Dentist',
  EntitySubtype.doctor: 'Doctor',
  EntitySubtype.stylist: 'Stylist',
  EntitySubtype.therapist: 'Therapist',
  EntitySubtype.physiotherapist: 'Physiotherapist',
  EntitySubtype.specialist: 'Medical Specialist',
  EntitySubtype.surgeon: 'Surgeon',
  EntitySubtype.appointment: 'Appointment',
  EntitySubtype.beauty: 'BEAUTY',
  EntitySubtype.fitnessActivity: 'FITNESS_ACTIVITY',
  EntitySubtype.healthGoal: 'HealthGoal',
  EntitySubtype.medical: 'MEDICAL',
  EntitySubtype.patient: 'Patient',
  EntitySubtype.appliance: 'Appliance',
  EntitySubtype.contractor: 'Contractor',
  EntitySubtype.furniture: 'Furniture',
  EntitySubtype.home: 'Home',
  EntitySubtype.room: 'Room',
  EntitySubtype.cleaning: 'CLEANING',
  EntitySubtype.cooking: 'COOKING',
  EntitySubtype.homeMaintenance: 'HOME_MAINTENANCE',
  EntitySubtype.tool: 'Tool',
  EntitySubtype.plant: 'Plant',
  EntitySubtype.garden: 'Garden',
  EntitySubtype.gardening: 'GARDENING',
  EntitySubtype.foodPlan: 'FoodPlan',
  EntitySubtype.recipe: 'Recipe',
  EntitySubtype.restaurant: 'Restaurant',
  EntitySubtype.food: 'Food',
  EntitySubtype.dryCleaners: 'DryCleaners',
  EntitySubtype.item: 'Item',
  EntitySubtype.clothing: 'Clothing',
  EntitySubtype.laundryPlan: 'LaundryPlan',
  EntitySubtype.bank: 'Bank',
  EntitySubtype.bankAccount: 'BankAccount',
  EntitySubtype.creditCard: 'CreditCard',
  EntitySubtype.finance: 'Finance',
  EntitySubtype.boat: 'Boat',
  EntitySubtype.car: 'Car',
  EntitySubtype.vehicleCar: 'vehicle_car',
  EntitySubtype.publicTransport: 'PublicTransport',
  EntitySubtype.motorcycle: 'Motorcycle',
  EntitySubtype.trip: 'Trip',
  EntitySubtype.accommodation: 'ACCOMMODATION',
  EntitySubtype.place: 'PLACE',
  EntitySubtype.driveTime: 'DriveTime',
  EntitySubtype.flight: 'Flight',
  EntitySubtype.hotelOrRental: 'HotelOrRental',
  EntitySubtype.rentalCar: 'RentalCar',
  EntitySubtype.stayWithFriend: 'StayWithFriend',
  EntitySubtype.taxiOrTransfer: 'TaxiOrTransfer',
  EntitySubtype.trainBusFerry: 'TrainBusFerry',
  EntitySubtype.travelPlan: 'TravelPlan',
  EntitySubtype.document: 'Document',
  EntitySubtype.passport: 'Passport',
  EntitySubtype.license: 'License',
  EntitySubtype.bankStatement: 'BankStatement',
  EntitySubtype.taxDocument: 'TaxDocument',
  EntitySubtype.contract: 'Contract',
  EntitySubtype.will: 'Will',
  EntitySubtype.medicalRecord: 'MedicalRecord',
  EntitySubtype.prescription: 'Prescription',
  EntitySubtype.resume: 'Resume',
  EntitySubtype.certificate: 'Certificate',
  EntitySubtype.familyMember: 'FamilyMember',
  EntitySubtype.other: 'other',
  EntitySubtype.general: 'general',
};
