// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaZxZGHEA8ksXtFsM8PqKtDIx2Q68uwZA',
    appId: '1:518781259229:web:30604a80d3d0a3c6b73a34',
    messagingSenderId: '518781259229',
    projectId: 'qaaaa-448c6',
    authDomain: 'qaaaa-448c6.firebaseapp.com',
    storageBucket: 'qaaaa-448c6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGdbpz5znq9lsVptLNUb5zBwNTsn0aGz0',
    appId: '1:518781259229:android:3aa5d415774eace6b73a34',
    messagingSenderId: '518781259229',
    projectId: 'qaaaa-448c6',
    storageBucket: 'qaaaa-448c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmByX6yMF0dJgJYlDsEPTHdLzCJnxScjk',
    appId: '1:518781259229:ios:856f14c4207fa094b73a34',
    messagingSenderId: '518781259229',
    projectId: 'qaaaa-448c6',
    storageBucket: 'qaaaa-448c6.firebasestorage.app',
    iosClientId: '518781259229-4d7dc92mqgt160ercnkc8103l6352sc2.apps.googleusercontent.com',
    iosBundleId: 'com.vuetapp.vuetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmByX6yMF0dJgJYlDsEPTHdLzCJnxScjk',
    appId: '1:518781259229:ios:856f14c4207fa094b73a34',
    messagingSenderId: '518781259229',
    projectId: 'qaaaa-448c6',
    storageBucket: 'qaaaa-448c6.firebasestorage.app',
    iosClientId: '518781259229-4d7dc92mqgt160ercnkc8103l6352sc2.apps.googleusercontent.com',
    iosBundleId: 'com.vuetapp.vuetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaZxZGHEA8ksXtFsM8PqKtDIx2Q68uwZA',
    appId: '1:518781259229:web:5fc25d2ecd186118b73a34',
    messagingSenderId: '518781259229',
    projectId: 'qaaaa-448c6',
    authDomain: 'qaaaa-448c6.firebaseapp.com',
    storageBucket: 'qaaaa-448c6.firebasestorage.app',
  );
}
