name: CodeRabbit Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  coderabbit-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Run CodeRabbit analysis
        uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.CODERABBIT_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false 